# Site
#url: http://michaelmanhire.com
url: http://localhost:4000

exclude: ["node_modules", "gulpfile.js", "package.json"]

# Outputting
markdown: kramdown
permalink: /:title
timezone: America/Los_Angeles

# Sass
sass:
  sass_dir: ./_scss
  style: compressed

# Front Matter defaults
defaults:
  scope:
    path: "" # an empty string here means all files in the project
    layout: "default"
